
import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Siya Saji
 */
public class PROPERTY_IMAGES_SLIDER extends javax.swing.JFrame {

    /**
     * Creates new form PROPERTY_IMAGES_SLIDER
     */
    
    //get the property id
    static int propertyId;
    
    //images list
    ArrayList<byte[]>imagesList;
    
    //the image index
    int index=0;
    
    public PROPERTY_IMAGES_SLIDER(int pId) {
        initComponents();
        
        this.propertyId=pId;
        
         // set border to the jlabel image
        Border jlabel_image_border =  BorderFactory.createMatteBorder(1,1,1,1, new Color(0,0,0));
        jLabel_image.setBorder(jlabel_image_border);
        
        // set border to the next & previous jlabel
        Border jlabel_nav_border =  BorderFactory.createMatteBorder(1,1,1,1, new Color(255,69,0));
//        jLabel_next.setBorder(jlabel_nav_border);
//        jLabel_previous.setBorder(jlabel_nav_border);
        
        
        //get the images using the hashmap
        HashMap<byte[],Integer> map = new P_PROPERTY().propertyImagesList(propertyId);
        imagesList = new ArrayList<>(map.keySet());
        
        displayImage(index);
    }

    

    
    //create a function to display the image by index
    public void displayImage(int imageIndex)
    {
        Image img= new ImageIcon(imagesList.get(imageIndex)).getImage().getScaledInstance(jLabel_image.getWidth(),jLabel_image.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(img);
        jLabel_image.setIcon(image);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_image = new javax.swing.JLabel();
        jLabel_previous = new javax.swing.JLabel();
        jLabel_next = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel_image.setBackground(new java.awt.Color(204, 204, 204));
        jLabel_image.setOpaque(true);

        jLabel_previous.setBackground(new java.awt.Color(255, 204, 204));
        jLabel_previous.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_previous.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_previous.setText("<");
        jLabel_previous.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 3, true));
        jLabel_previous.setOpaque(true);
        jLabel_previous.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_previousMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_previousMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_previousMouseExited(evt);
            }
        });

        jLabel_next.setBackground(new java.awt.Color(255, 204, 204));
        jLabel_next.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_next.setText(">");
        jLabel_next.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 102), 3, true));
        jLabel_next.setOpaque(true);
        jLabel_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_nextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_nextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_nextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_previous, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_next, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_next, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_previous, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nextMouseClicked
        // show the next image
        index++;
        
        if(index>=imagesList.size()) index= imagesList.size() -1;
        
        displayImage(index);
    }//GEN-LAST:event_jLabel_nextMouseClicked

    private void jLabel_previousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_previousMouseClicked
        // show the previous image
        index--;
        
        if(index< 0) index= 0;
        
        displayImage(index);
    }//GEN-LAST:event_jLabel_previousMouseClicked

    private void jLabel_nextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nextMouseEntered
        
        jLabel_next.setBackground(new Color(255,69,0));
        jLabel_next.setForeground(Color.white);
        
    }//GEN-LAST:event_jLabel_nextMouseEntered

    private void jLabel_nextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_nextMouseExited
        jLabel_next.setBackground(new Color(255,204,204));
        jLabel_next.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_nextMouseExited

    private void jLabel_previousMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_previousMouseEntered
        jLabel_previous.setBackground(new Color(255,69,0));
        jLabel_previous.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_previousMouseEntered

    private void jLabel_previousMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_previousMouseExited
        jLabel_previous.setBackground(new Color(255,204,204));
        jLabel_previous.setForeground(Color.black);
    }//GEN-LAST:event_jLabel_previousMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PROPERTY_IMAGES_SLIDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PROPERTY_IMAGES_SLIDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PROPERTY_IMAGES_SLIDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PROPERTY_IMAGES_SLIDER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PROPERTY_IMAGES_SLIDER(propertyId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JLabel jLabel_next;
    private javax.swing.JLabel jLabel_previous;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
