
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AVS Vastalya
 */
public class SEARCH_WINDOW extends javax.swing.JFrame {

    /**
     * Creates new form SEARCH_WINDOW
     */
    
    P_TYPE type = new P_TYPE();
    HashMap<String, Integer> map = type.getTypeMap();
    public SEARCH_WINDOW() {
        initComponents();
        fillJtableWithPropertiesData();
        jTable1.setRowHeight(30);
        
        // set border to the app name lable
        Border panel_title_border =  BorderFactory.createMatteBorder(0,0,3,0, new Color(235,125,22));
        jPanel_title.setBorder(panel_title_border);
        
        //set border to the jbuttons
        Border button_border =  BorderFactory.createMatteBorder(2,2,2,2, new Color(255,255,255));
        //jButton_search_by_type.setBorder(button_border);
        //jButton_search_by_price.setBorder(button_border);
        //jButton_show_property.setBorder(button_border);
        
        //populate the combobox
        bindCombo();
        
        //populate jCombobox-price
        bindComboBox_price();
       
    }
    
    //create a function to populate the jcombobox with types of data
    public void bindCombo()
    {
        for(String s : map.keySet())
        {
            jComboBox_type.addItem(s);
        }    
    }
    
    public void bindComboBox_price()
    {
        jComboBox_price.addItem("Below 5000");
        jComboBox_price.addItem("5000 - 10000");
        jComboBox_price.addItem("10000 - 20000");
        jComboBox_price.addItem("Above 20000");
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_title = new javax.swing.JPanel();
        jLabel_title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_search_by_type = new javax.swing.JButton();
        jComboBox_type = new javax.swing.JComboBox<>();
        jButton_show_property = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_firstname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_lastname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_phone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_description = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_address = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_address1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton_show_property_photos = new javax.swing.JButton();
        jComboBox_price = new javax.swing.JComboBox<>();
        jButton_search_by_price = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 248, 220));

        jPanel_title.setBackground(new java.awt.Color(247, 197, 102));

        jLabel_title.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel_title.setForeground(new java.awt.Color(108, 3, 69));
        jLabel_title.setText("Search Property");

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addGap(451, 451, 451)
                .addComponent(jLabel_title, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_title, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("Type:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel6.setText("Price:");

        jButton_search_by_type.setBackground(new java.awt.Color(151, 27, 105));
        jButton_search_by_type.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_search_by_type.setForeground(new java.awt.Color(255, 255, 255));
        jButton_search_by_type.setText("Search");
        jButton_search_by_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_search_by_typeActionPerformed(evt);
            }
        });

        jComboBox_type.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_typeActionPerformed(evt);
            }
        });

        jButton_show_property.setBackground(new java.awt.Color(30, 169, 77));
        jButton_show_property.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_show_property.setForeground(new java.awt.Color(255, 255, 255));
        jButton_show_property.setText("SHOW ALL PROPERTIES");
        jButton_show_property.setToolTipText("");
        jButton_show_property.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_show_property.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_show_propertyActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Owner Details:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel4.setText("First Name:");

        jTextField_firstname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_firstnameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel5.setText("Last Name:");

        jTextField_lastname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lastnameActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel7.setText("Phone No.: ");

        jTextField_phone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_phoneActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel8.setText("Email:");

        jTextField_email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_emailActionPerformed(evt);
            }
        });

        jTextArea_description.setColumns(20);
        jTextArea_description.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea_description.setRows(5);
        jScrollPane2.setViewportView(jTextArea_description);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Description:");

        jTextArea_address.setColumns(20);
        jTextArea_address.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea_address.setRows(5);
        jScrollPane4.setViewportView(jTextArea_address);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Address:");

        jTextArea_address1.setColumns(20);
        jTextArea_address1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextArea_address1.setRows(5);
        jScrollPane1.setViewportView(jTextArea_address1);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setText("Address:");

        jButton_show_property_photos.setBackground(new java.awt.Color(255, 102, 0));
        jButton_show_property_photos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_show_property_photos.setForeground(new java.awt.Color(255, 255, 255));
        jButton_show_property_photos.setText("SHOW PROPERTY PHOTOS");
        jButton_show_property_photos.setToolTipText("");
        jButton_show_property_photos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_show_property_photos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_show_property_photosActionPerformed(evt);
            }
        });

        jComboBox_price.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jButton_search_by_price.setBackground(new java.awt.Color(151, 27, 105));
        jButton_search_by_price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_search_by_price.setForeground(new java.awt.Color(255, 255, 255));
        jButton_search_by_price.setText("Search");
        jButton_search_by_price.setBorder(null);
        jButton_search_by_price.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_search_by_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_search_by_priceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(149, 149, 149)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton_show_property_photos)
                                .addComponent(jButton_show_property, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(35, 35, 35)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBox_price, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_type, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_search_by_type, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_search_by_price, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(321, 321, 321))))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(9, 9, 9)
                            .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(8, 8, 8)
                            .addComponent(jTextField_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_show_property, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_search_by_type, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_type, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox_price, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_search_by_price, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton_show_property_photos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_show_propertyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_show_propertyActionPerformed
        fillJtableWithPropertiesData();
    }//GEN-LAST:event_jButton_show_propertyActionPerformed

    private void jButton_search_by_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_search_by_typeActionPerformed

        // search property by type
        //and display the property data
        try {
            int propertyType = map.get(jComboBox_type.getSelectedItem().toString());
            
            ArrayList<P_PROPERTY> propertyList = new P_PROPERTY().propertiesListByType(propertyType);
            
            //the jtable columns
            String[] colNames = {"ID","Type","Sq ft.","OwnerId","Price","Address", "Bedrooms", "Bathrooms", "Age", "Balcony", "description"};

            //the jtable row
        //properityList.size()= the size of the arrayList
        Object[][] rows = new Object[propertyList.size()][11];
        
        //add data from the list to the rows
        for(int i=0; i< propertyList.size(); i++)
        {
            rows[i][0]= propertyList.get(i).getId();
            //rows[i][1]= propertyList.get(i).getType();
            String typeName = type.getTypeName(propertyList.get(i).getType());
            rows[i][1] = typeName != null ? typeName : "";
            rows[i][2]= propertyList.get(i).getSize();
            rows[i][3]= propertyList.get(i).getOwnerId();
            rows[i][4]= propertyList.get(i).getPrice();
            rows[i][5]= propertyList.get(i).getAddress();
            rows[i][6]= propertyList.get(i).getBedrooms();
            rows[i][7]= propertyList.get(i).getBathrooms();
            rows[i][8]= propertyList.get(i).getAge();
            if(propertyList.get(i).isBalcony())
            {
                rows[i][9]= "YES";
            }
            else{
                rows[i][9]= "NO";
            }
                
            rows[i][10]= propertyList.get(i).getDescription();
        }


            DefaultTableModel model = new DefaultTableModel(rows, colNames);
            jTable1.setModel(model);
           
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_search_by_typeActionPerformed

    private void jTextField_firstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_firstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_firstnameActionPerformed

    private void jTextField_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lastnameActionPerformed

    private void jTextField_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_phoneActionPerformed

    private void jTextField_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emailActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //fill the discription and address field area
        int SelectedRowIndex= jTable1.getSelectedRow();
        int ownerId=(int) jTable1.getValueAt(SelectedRowIndex, 3);
        
        jTextArea_address.setText(jTable1.getValueAt(SelectedRowIndex, 5).toString());
        jTextArea_description.setText(jTable1.getValueAt(SelectedRowIndex, 10).toString());
        P_OWNER owner =  new P_OWNER();
        P_OWNER ownerDetails=owner.getOwnerDetails(ownerId);
        jTextField_firstname.setText(ownerDetails.getFristName());
        jTextField_lastname.setText(ownerDetails.getLastName());
        jTextField_email.setText(ownerDetails.getEmail());
        jTextField_phone.setText(ownerDetails.getPhone());
        jTextArea_address1.setText(ownerDetails.getAddress());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_show_property_photosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_show_property_photosActionPerformed
        // OPEN THE IMAGE SLIDER WINDOW TO SHOW ALL THE PHOTOS BELONGING TO THE PROPERTY WITH ID= proeprty id
        try{
        PreparedStatement ps;
        ResultSet rs;
            
            //set the property id
             int rowIndex= jTable1.getSelectedRow(); //selected jtable row index
            int property_id= Integer.valueOf(jTable1.getValueAt(rowIndex,0).toString()); //get the id from the jtable
                
            String checkImagesQuery = "SELECT COUNT(*) FROM property_images WHERE property_id = ?";
             try{
                 ps = THE_CONNECTION.getTheConnection().prepareStatement(checkImagesQuery);
                ps.setInt(1, property_id);
                rs = ps.executeQuery();
                if (rs.next()) {
                int imageCount = rs.getInt(1);
                if (imageCount > 0) {
                    // Property has images, open the image slider window
                    PROPERTY_IMAGES_SLIDER imagesSliderform = new PROPERTY_IMAGES_SLIDER(property_id);
                    imagesSliderform.setVisible(true);
                    imagesSliderform.pack();
                    imagesSliderform.setLocationRelativeTo(null);
                    imagesSliderform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                } else {
                    JOptionPane.showMessageDialog(null, "This property does not have any images to show", "No images", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "This property does not have any images to show", "No images", JOptionPane.INFORMATION_MESSAGE);
        }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Select the property first", "property not selected", 2);

        }
    }//GEN-LAST:event_jButton_show_property_photosActionPerformed

    private void jButton_search_by_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_search_by_priceActionPerformed
        // search property by id
        //and display the property data
         // Map displayed items to corresponding indexes
        HashMap<String, Integer> priceRangeIndexMap = new HashMap<>();
        priceRangeIndexMap.put("Below 5000", 0);
        priceRangeIndexMap.put("5000 - 10000", 1);
        priceRangeIndexMap.put("10000 - 20000", 2);
        priceRangeIndexMap.put("Above 20000", 3);
        
        try {
            // Get the selected item from the JComboBox
        String selectedPriceRange = (String) jComboBox_price.getSelectedItem();

        // Retrieve the corresponding index from the map
        int selectedIndex = priceRangeIndexMap.get(selectedPriceRange);
            ArrayList<P_PROPERTY> propertyList = new P_PROPERTY().propertiesListByPrice(selectedIndex);
            
            //the jtable columns
            String[] colNames = {"ID","Type","Sq ft.","OwnerId","Price","Address", "Bedrooms", "Bathrooms", "Age", "Balcony", "description"};

            //the jtable row
        //properityList.size()= the size of the arrayList
        Object[][] rows = new Object[propertyList.size()][11];
        
        //add data from the list to the rows
        for(int i=0; i< propertyList.size(); i++)
        {
            rows[i][0]= propertyList.get(i).getId();
            //rows[i][1]= propertyList.get(i).getType();
            String typeName = type.getTypeName(propertyList.get(i).getType());
            rows[i][1] = typeName != null ? typeName : "";
            rows[i][2]= propertyList.get(i).getSize();
            rows[i][3]= propertyList.get(i).getOwnerId();
            rows[i][4]= propertyList.get(i).getPrice();
            rows[i][5]= propertyList.get(i).getAddress();
            rows[i][6]= propertyList.get(i).getBedrooms();
            rows[i][7]= propertyList.get(i).getBathrooms();
            rows[i][8]= propertyList.get(i).getAge();
            if(propertyList.get(i).isBalcony())
            {
                rows[i][9]= "YES";
            }
            else{
                rows[i][9]= "NO";
            }
                
            rows[i][10]= propertyList.get(i).getDescription();
        }


            DefaultTableModel model = new DefaultTableModel(rows, colNames);
            jTable1.setModel(model);
           
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton_search_by_priceActionPerformed

    private void jComboBox_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_typeActionPerformed

    
    //create a function to poulate the jTable with properties data
    public void fillJtableWithPropertiesData()
    {
        P_PROPERTY property = new P_PROPERTY();
        ArrayList<P_PROPERTY> propertyList = property.propertiesListForTenent();
        
        //the jtable columns
        String[] colNames = {"ID","Type","Square_Feet","OwnerId","Price","Address", "Bedrooms", "Bathrooms", "Age", "Balcony", "description"};
        
        //the jtable row
        //properityList.size()= the size of the arrayList
        Object[][] rows = new Object[propertyList.size()][11];
        
        //add data from the list to the rows
        for(int i=0; i< propertyList.size(); i++)
        {
            rows[i][0]= propertyList.get(i).getId();
            //rows[i][1]= propertyList.get(i).getType();
            String typeName = type.getTypeName(propertyList.get(i).getType());
            rows[i][1] = typeName != null ? typeName : "";
            rows[i][2]= propertyList.get(i).getSize();
            rows[i][3]= propertyList.get(i).getOwnerId();
            rows[i][4]= propertyList.get(i).getPrice();
            rows[i][5]= propertyList.get(i).getAddress();
            rows[i][6]= propertyList.get(i).getBedrooms();
            rows[i][7]= propertyList.get(i).getBathrooms();
            rows[i][8]= propertyList.get(i).getAge();
            if(propertyList.get(i).isBalcony())
            {
                rows[i][9]= "YES";
            }
            else{
                rows[i][9]= "NO";
            }
                
            rows[i][10]= propertyList.get(i).getDescription();
        }
        
        DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable1.setModel(model);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SEARCH_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SEARCH_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SEARCH_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SEARCH_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SEARCH_WINDOW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_search_by_price;
    private javax.swing.JButton jButton_search_by_type;
    private javax.swing.JButton jButton_show_property;
    private javax.swing.JButton jButton_show_property_photos;
    private javax.swing.JComboBox<String> jComboBox_price;
    private javax.swing.JComboBox<String> jComboBox_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_title;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_address;
    private javax.swing.JTextArea jTextArea_address1;
    private javax.swing.JTextArea jTextArea_description;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_firstname;
    private javax.swing.JTextField jTextField_lastname;
    private javax.swing.JTextField jTextField_phone;
    // End of variables declaration//GEN-END:variables
}
