
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AVS Vastalya
 */
public class TENENT_MAIN_WINDOW extends javax.swing.JFrame {

    /**
     * Creates new form TENENT_MAIN_WINDOW
     */
    
    P_TYPE type = new P_TYPE();
    
    public TENENT_MAIN_WINDOW() {
        initComponents();
        this.setLocationRelativeTo(null);
        //populate the jtable
        fillJtableWithPropertiesData();
        jLabel_app_icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png")));
        //set menu items border
        Border menu_items_border =  BorderFactory.createMatteBorder(0,0,1,0, Color.yellow);
//        jLabel_property_photos.setBorder(menu_items_border);
//        jLabel_search.setBorder(menu_items_border);
//        Border logout_border =  BorderFactory.createMatteBorder(1,0,1,0, Color.yellow);
//        jLabel_logout.setBorder(logout_border);
        
        Border border =  BorderFactory.createMatteBorder(0,0,0,1, new Color(108,3,69));
        jPanel6.setBorder(border);
        
        //set row height
        jTable1.setRowHeight(30);
        
        //change the table slected background
        jTable1.setSelectionBackground(new Color(255,153,153));
        //change the width of the column
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(40);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(35);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(35);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(15);
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(20);
        jTable1.getColumnModel().getColumn(10).setPreferredWidth(150);
        //jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
    }
    
    //create a function to poulate the jTable with properties data
    public void fillJtableWithPropertiesData()
    {
        P_PROPERTY property = new P_PROPERTY();
        ArrayList<P_PROPERTY> propertyList = property.propertiesListForTenent();
        
       HashMap<String, Integer> typeMap = new P_TYPE().getTypeMap();
        
        //the jtable columns
        String[] colNames = {"ID","Type","Square_Feet","OwnerId","Price","Address", "Bedrooms", "Bathrooms", "Age", "Balcony", "description"};
        
        //the jtable row
        //properityList.size()= the size of the arrayList
        Object[][] rows = new Object[propertyList.size()][11];
        
        //add data from the list to the rows
        for(int i=0; i< propertyList.size(); i++)
        {
            rows[i][0]= propertyList.get(i).getId();
            //rows[i][1]= propertyList.get(i).getType();
            String typeName = type.getTypeName(propertyList.get(i).getType());
            rows[i][1] = typeName != null ? typeName : "";
            rows[i][2]= propertyList.get(i).getSize();
            rows[i][3]= propertyList.get(i).getOwnerId();
            rows[i][4]= propertyList.get(i).getPrice();
            rows[i][5]= propertyList.get(i).getAddress();
            rows[i][6]= propertyList.get(i).getBedrooms();
            rows[i][7]= propertyList.get(i).getBathrooms();
            rows[i][8]= propertyList.get(i).getAge();
            if(propertyList.get(i).isBalcony())
            {
                rows[i][9]= "YES";
            }
            else{
                rows[i][9]= "NO";
            }
                
            rows[i][10]= propertyList.get(i).getDescription();
        }
        
        DefaultTableModel model = new DefaultTableModel(rows, colNames);
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_app_icon = new javax.swing.JLabel();
        jLabel_app_name = new javax.swing.JLabel();
        jLabel_app_icon1 = new javax.swing.JLabel();
        jLabel_app_name1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel_property_photos = new javax.swing.JLabel();
        jLabel_logout = new javax.swing.JLabel();
        jLabel_search = new javax.swing.JLabel();
        jPanel_title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_app_icon2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel_description = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_address = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_description = new javax.swing.JTextArea();

        jLabel_app_icon.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_app_icon.setOpaque(true);

        jLabel_app_name.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_app_name.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel_app_name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_app_name.setText("House renting");

        jLabel_app_icon1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_app_icon1.setOpaque(true);

        jLabel_app_name1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_app_name1.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel_app_name1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_app_name1.setText("House renting");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 248, 220));

        jLabel_property_photos.setBackground(new java.awt.Color(255, 248, 220));
        jLabel_property_photos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_property_photos.setForeground(new java.awt.Color(108, 3, 69));
        jLabel_property_photos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_property_photos.setText("PROPERTY PHOTOS");
        jLabel_property_photos.setOpaque(true);
        jLabel_property_photos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_property_photosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_property_photosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_property_photosMouseExited(evt);
            }
        });

        jLabel_logout.setBackground(new java.awt.Color(255, 80, 37));
        jLabel_logout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_logout.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_logout.setText("Logout");
        jLabel_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_logout.setOpaque(true);
        jLabel_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_logoutMouseExited(evt);
            }
        });

        jLabel_search.setBackground(new java.awt.Color(255, 248, 220));
        jLabel_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_search.setForeground(new java.awt.Color(108, 3, 69));
        jLabel_search.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_search.setText("SEARCH");
        jLabel_search.setOpaque(true);
        jLabel_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_searchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_searchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_property_photos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
            .addComponent(jLabel_search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_search, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_property_photos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel_title.setBackground(new java.awt.Color(252, 172, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALL Available Properties");

        jLabel_app_icon2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_app_icon2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_app_icon2.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DORMIFY");

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_app_icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addGroup(jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_titleLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel_titleLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 19, Short.MAX_VALUE))))
                    .addGroup(jPanel_titleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_app_icon2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 248, 220));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Address:");

        jLabel_description.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_description.setText("Description:");

        jTextArea_address.setColumns(20);
        jTextArea_address.setRows(5);
        jScrollPane2.setViewportView(jTextArea_address);

        jTextArea_description.setColumns(20);
        jTextArea_description.setRows(5);
        jScrollPane3.setViewportView(jTextArea_description);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_description, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242)))
                .addGap(66, 66, 66))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_description, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //display the property address and description in text fields
        int SelectedRowIndex= jTable1.getSelectedRow();
        jTextArea_address.setText(jTable1.getValueAt(SelectedRowIndex, 5).toString());
        jTextArea_description.setText(jTable1.getValueAt(SelectedRowIndex, 10).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel_property_photosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_property_photosMouseClicked
        //open property imaged winodow
        TENENT_PROPERTY_IMAGES_WINDOW propertyImagesform = new TENENT_PROPERTY_IMAGES_WINDOW();            
        propertyImagesform.setVisible(true);
        propertyImagesform.pack();     
        propertyImagesform.setLocationRelativeTo(null);
        propertyImagesform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_property_photosMouseClicked

    private void jLabel_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutMouseClicked
        //open the initial page

        INITIAL_WINDOW typeform = new INITIAL_WINDOW();

        typeform.setVisible(true);
        typeform.pack();
        //typeform.setExtendedState(JFrame.MAXIMIZED_BOTH);
        typeform.setLocationRelativeTo(null);
        typeform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_logoutMouseClicked

    private void jLabel_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutMouseEntered
//        jLabel_logout.setBackground(new Color(108,3,69));
//        jLabel_logout.setForeground(new Color(255,248,220));
    }//GEN-LAST:event_jLabel_logoutMouseEntered

    private void jLabel_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutMouseExited
//        jLabel_logout.setBackground(new Color(255,248,220));
//        jLabel_logout.setForeground(new Color(108,3,69));
    }//GEN-LAST:event_jLabel_logoutMouseExited

    private void jLabel_property_photosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_property_photosMouseEntered
        jLabel_property_photos.setBackground(new Color(108,3,69));
        jLabel_property_photos.setForeground(new Color(255,248,220));
    }//GEN-LAST:event_jLabel_property_photosMouseEntered

    private void jLabel_property_photosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_property_photosMouseExited
        jLabel_property_photos.setBackground(new Color(255,248,220));
        jLabel_property_photos.setForeground(new Color(108,3,69));
    }//GEN-LAST:event_jLabel_property_photosMouseExited

    private void jLabel_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_searchMouseClicked
        SEARCH_WINDOW searchform = new SEARCH_WINDOW();
                    
        searchform.setVisible(true);
        searchform.pack();         
        searchform.setLocationRelativeTo(null);
        searchform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_searchMouseClicked

    private void jLabel_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_searchMouseEntered
        jLabel_search.setBackground(new Color(108,3,69));
        jLabel_search.setForeground(new Color(255,248,220));
    }//GEN-LAST:event_jLabel_searchMouseEntered

    private void jLabel_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_searchMouseExited
        jLabel_search.setBackground(new Color(255,248,220));
        jLabel_search.setForeground(new Color(108,3,69));
    }//GEN-LAST:event_jLabel_searchMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TENENT_MAIN_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TENENT_MAIN_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TENENT_MAIN_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TENENT_MAIN_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TENENT_MAIN_WINDOW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel_app_icon;
    private javax.swing.JLabel jLabel_app_icon1;
    private javax.swing.JLabel jLabel_app_icon2;
    private javax.swing.JLabel jLabel_app_name;
    private javax.swing.JLabel jLabel_app_name1;
    private javax.swing.JLabel jLabel_description;
    private javax.swing.JLabel jLabel_logout;
    private javax.swing.JLabel jLabel_property_photos;
    private javax.swing.JLabel jLabel_search;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_address;
    private javax.swing.JTextArea jTextArea_description;
    // End of variables declaration//GEN-END:variables
}
